name: Provision Netlify site

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Provision site
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: echo 'IyEvdXNyL2Jpbi9lbnYgYmFzaApzZXQgLWV1byBwaXBlZmFpbApzdGF0dXM9JChjdXJsIC0tc2lsZW50IC0tb3V0cHV0IC9kZXYvbnVsbCAtLXdyaXRlLW91dCAnJXtodHRwX2NvZGV9JyAtLWhlYWRlciAiQXV0aG9yaXphdGlvbjogQmVhcmVyICR7TkVUTElGWV9BVVRIX1RPS0VOfSIgaHR0cHM6Ly9hcGkubmV0bGlmeS5jb20vYXBpL3YxL3NpdGVzKQpwcmludGYgJyVzXG4nICIkc3RhdHVzIgp0ZXN0ICIkc3RhdHVzIiA9ICIyMDAiCnJlc3BvbnNlPSQoY3VybCAtLWZhaWwgLS1zaG93LWVycm9yIC0tcmVxdWVzdCBQT1NUIC0taGVhZGVyICJBdXRob3JpemF0aW9uOiBCZWFyZXIgJHtORVRMSUZZX0FVVEhfVE9LRU59IiAtLWhlYWRlciAiQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi9qc29uIiAtLWRhdGEgJ3sibmFtZSI6ImJsYWNrcy1yZXAtdG9vbC12MSIsImFjY291bnRfc2x1ZyI6ImNyYWlnbWNnZW93bjEifScgaHR0cHM6Ly9hcGkubmV0bGlmeS5jb20vYXBpL3YxL3NpdGVzKQpzaXRlX2lkPSQocHJpbnRmICclcycgIiRyZXNwb25zZSIgfCBqcSAtZXIgJy5pZCcpCnByaW50ZiAnTkVUTElGWV9TSVRFX0lEPSVzXG4nICIkc2l0ZV9pZCIK' | base64 --decode | bash
